#ifndef LITE_PACK_1DARRAY_TYPE_H
#define LITE_PACK_1DARRAY_TYPE_H

enum lip_1darray_type
{
    LIP_1DARRAY_INT8,
    LIP_1DARRAY_INT16,
    LIP_1DARRAY_INT32,
    LIP_1DARRAY_INT64,
    LIP_1DARRAY_UINT8,
    LIP_1DARRAY_UINT16,
    LIP_1DARRAY_UINT32,
    LIP_1DARRAY_UINT64,
    LIP_1DARRAY_F32,
    LIP_1DARRAY_F64
};

#endif
